# House Price Prediction

In this project, I will build a machine learning model to predict house prices.
The dataset is based on apartment listings from Azerbaijan, mainly Baku.

The main goal is to practice a full regression workflow:
- loading a real dataset
- exploring the data
- preprocessing features
- training models
- evaluating model performance

## 1. Import Libraries

Import libraries that will be used for data analysis, visualization, preprocessing, and machine learning.

In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_openml

## 2. Load the Dataset

I saved the Azerbaijan apartment price dataset inside the `data` folder. 
It includes information such as location, number of rooms, apartment area, floor, building type, repair status, bill of sale, mortgage availability, and price.
The file is loaded with pandas from a local CSV file.

In [2]:
df = pd.read_csv("data/BakuApartmentData.csv", index_col=0)
df.head()

,price,location,rooms,square,floor,new_building,has_repair,has_bill_of_sale,has_mortgage
0,177000,Həzi Aslanov m.,4,117.0,12/16,1,1,1,1
1,190000,Şah İsmayıl Xətai m.,2,80.0,5/16,1,1,1,1
2,430000,Elmlər Akademiyası m.,4,170.0,3/17,1,1,1,1
3,465000,Elmlər Akademiyası m.,4,186.0,9/15,1,1,1,1
4,265500,28 May m.,3,96.0,8/16,1,1,1,1

The first unnamed column in the CSV is only an old index, so I used `index_col=0` while reading the file.

The target column is `price`. This is the value that the model will try to predict later.

## 3. Basic Dataset Information

Now I check num of rows and columns in the dataset.

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 458075
Columns: 9

In [4]:
df.columns

Index(['price', 'location', 'rooms', 'square', 'floor', 'new_building',
       'has_repair', 'has_bill_of_sale', 'has_mortgage'],
      dtype='str')

I will check the data types. This is important because numeric and categorical columns will need different preprocessing steps later.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 458075 entries, 0 to 458074
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   price             458075 non-null  int64
 1   location          458075 non-null  str
 2   rooms             458075 non-null  int64
 3   square            458075 non-null  float64
 4   floor             458075 non-null  str
 5   new_building      458075 non-null  int64
 6   has_repair        458075 non-null  int64
 7   has_bill_of_sale  458075 non-null  int64
 8   has_mortgage      458075 non-null  int64
dtypes: float64(1), int64(6), str(2)
memory usage: 31.5 MB

## 4. Summary Statistics

Here I look at simple summary statistics for numeric columns, such as mean, minimum, maximum, and standard deviation.

In [6]:
df.describe()

,price,rooms,square,new_building,has_repair,has_bill_of_sale,has_mortgage
count,4.580750e+05,458075.000000,458075.000000,458075.000000,458075.000000,458075.000000,458075.000000
mean,2.418705e+05,2.829873,110.213341,0.359572,0.423151,0.518509,0.461505
std,1.845307e+05,0.896957,59.326530,0.479876,0.494060,0.499658,0.498516
min,9.600000e+03,1.000000,12.000000,0.000000,0.000000,0.000000,0.000000
25%,1.450000e+05,2.000000,70.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000e+05,3.000000,100.000000,0.000000,0.000000,1.000000,0.000000
75%,2.880000e+05,3.000000,135.000000,1.000000,1.000000,1.000000,1.000000
max,8.075000e+06,20.000000,1600.000000,1.000000,1.000000,1.000000,1.000000

## 5. Missing Values

Finally, I check missing values. This will help me decide what preprocessing steps are needed in the next parts of the project.

If a column has missing values, I will later decide whether to fill them, remove rows, or handle them with a preprocessing pipeline.

In [7]:
missing_values = df.isnull().sum()

missing_values

price               0
location            0
rooms               0
square              0
floor               0
new_building        0
has_repair          0
has_bill_of_sale    0
has_mortgage        0
dtype: int64

In [8]:
missing_values.sort_values(ascending=False)

price               0
location            0
rooms               0
square              0
floor               0
new_building        0
has_repair          0
has_bill_of_sale    0
has_mortgage        0
dtype: int64

This check shows which columns have missing data and how many missing values each column contains.
In the preprocessing step, I will handle missing values before training the models.